apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: benchmark
  name: benchmark
  namespace: postgres-operator
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: benchmark
    spec:
      containers:
      - image: quay.io/jlpadilla/benchmark-postgres:latest
        imagePullPolicy: Always
        name: benchmark
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hippo-pguser-hippo
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30